stages:
  - push-to-github

sync-to-github:
  stage: push-to-github
  image: alpine/git:latest
  variables:
    GIT_CURL_VERBOSE: "1"
  script:
    - set -x
    - echo "Pushing to GitHub..."
    - git remote add github https://DaniBr:${GITHUB_TOKEN}@github.com/DaniBr/relative-time-element.git
    - git push --mirror github
  only:
    - main
